export const dataContinents = [
  {
    id: 1,
    name: "Europa",
    description: "O continente mais antigo.",
    bg_url: "./continents/europe.png",
  },
  {
    id: 2,
    name: "Asia",
    description: "Lorem Ipsum",
    bg_url: "./continents/asia.png",
  },
  {
    id: 3,
    name: "América do sul",
    description: "Lorem Ipsum",
    bg_url: "./continents/south_america.png",
  },
  {
    id: 4,
    name: "América do norte",
    description: "Lorem Ipsum",
    bg_url: "./continents/north_america.png",
  },
  {
    id: 5,
    name: "Africa",
    description: "Lorem Ipsum",
    bg_url: "./continents/africa.png",
  },
  {
    id: 6,
    name: "Oceania",
    description: "Lorem Ipsum",
    bg_url: "./continents/oceania.png",
  },
];

export const dataCountries = [
  {
    id: 1,
    name: "Europa",
    description:
      "A Europa é, por convenção, um dos seis continentes do mundo. Compreendendo a península ocidental da Eurásia, a Europa geralmente divide-se da Ásia a leste pela divisória de águas dos montes Urais, o rio Ural, o mar Cáspio, o Cáucaso, e o mar Negro a sudeste",
    bg_url: "./continents/europe.png",
    countries: [
      {
        id: 1,
        name: "Reino Unido",
        capital: "Londres",
        capa: "./countries/capa/capa_ru.png",
        flag: "./countries/flag/reino_unido.png",
      },
      {
        id: 1,
        name: "França",
        capital: "París",
        capa: "./countries/capa/capa_franca.png",
        flag: "./countries/flag/franca.png",
      },
      {
        id: 1,
        name: "Itália",
        capital: "Roma",
        capa: "./countries/capa/capa_italia.png",
        flag: "./countries/flag/italia.png",
      },
      {
        id: 1,
        name: "República Tcheca",
        capital: "Praga",
        capa: "./countries/capa/capa_rt.png",
        flag: "./countries/flag/republica_tcheca.png",
      },
      {
        id: 1,
        name: "Holanda",
        capital: "Amsterdâ",
        capa: "./countries/capa/capa_holanda.png",
        flag: "./countries/flag/holanda.png",
      },
    ],
  },
  {
    id: 2,
    name: "Asia",
    description:
      "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos.",
    bg_url: "./continents/asia.png",
    countries: [
      {
        id: 1,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 2,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 3,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 4,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 5,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
    ],
  },
  {
    id: 3,
    name: "América do sul",
    description:
      "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos.",
    bg_url: "./continents/south_america.png",
    countries: [
      {
        id: 1,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 2,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 3,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 4,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 5,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
    ],
  },
  {
    id: 4,
    name: "América do norte",
    description:
      "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos.",
    bg_url: "./continents/north_america.png",
    countries: [
      {
        id: 1,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 2,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 3,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 4,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 5,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
    ],
  },
  {
    id: 5,
    name: "Africa",
    description:
      "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos.",
    bg_url: "./continents/africa.png",
    countries: [
      {
        id: 1,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 2,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 3,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 4,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 5,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
    ],
  },
  {
    id: 6,
    name: "Oceania",
    description:
      "Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos.",
    bg_url: "./continents/oceania.png",
    countries: [
      {
        id: 1,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 2,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 3,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 4,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
      {
        id: 5,
        name: "País",
        capital: "Capital",
        capa: "",
        flag: "",
      },
    ],
  },
];
